name: Build
on: [push, pull_request]
jobs:
  build:
    name: build-linux-amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: ["386", "amd64", "arm", "arm64"]
        exclude:
          - os: darwin
            arch: "386"
          - os: darwin
            arch: "arm"
          - os: darwin
            arch: "arm64"
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Build
        run: go build ./cmd/grterm
        env:
          GOARCH: ${{ matrix.arch }}
          GOOS: ${{ matrix.os }}
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: grterm-${{ matrix.os }}-${{ matrix.arch }}
          path: grterm
